### ISSUE TITLE
Possible Feature Request - "One to Many" Relationships

### ISSUE THREAD

**Issue by jjmias** [tlaitinen/yesod-dsl#37]
Hello,

We are trying to define a GET request that returns all events and on each event it returns all multimedia on that event.  I don't know if this is currently possible or out of the scope of the library, but I think it would be a great thing to add since we are maintaining two APIs.

We are currently using the following to get all events in our .ydsl file:

```
route /events {
    get {
        select e.id, e.*, u.username
        from Invitation as i
        inner join Event as e
        on i.eventId = e.id
        inner join User as u
        on e.ownerId = u.id
        where i.userId = $auth.id;
    }
}
```

What we want to do is add an array of multimedia to this request.  So the response would be something like:

```
[
{ name: "Event's Name"
, id: "Event's Id"
, multimedia: [{name: "Multimedia's Name", id: "Multimedia's Id", ...}, ...],
...
},
...
]
```

Is it possible to update our code to get this type of response?

**Comment by tlaitinen** [comment]
Currently the tool implicitly assumes that a GET handler will just wrap a single SQL SELECT result into a JSON object. If you don't mind repetition in the data, namely Event.name and Event.id, you could add another join and then you'd have all the necessary data. The returned JSON array would still be "flat", e.g.[ { eventName: "Event's Name", eventId: "Event's id", multimediaName: "Multimedia's Name", multimediaId : "Multimedia's Id" }, ... ]. 

One easy option would be to transform the JSON array into whatever the client likes best (see https://github.com/tlaitinen/yesod-dsl/issues/20 ). 

A slightly more complicated alternative would be to use something like ```json_agg(row_to_json((multimedia.id, multimedia.name)))``` but it's available only with PostgreSQL. This would avoid data duplication at server-side. 

I'm inclined towards the former because it works with all SQL backends and is easier to implement. The latter could be added later own if needed. 

What do you think=

**Comment by jjmias** [comment]
@tlaitinen As you mention, having the JSON array return "flat" has issues with repetition of data.  If an event had a lot of multimedia then there is going to be many instances of that event to iterate through on the client side.  This is something we are trying to avoid with this request since we could always just get all events and then make separate requests per event to get all multimedia on that event.  Obviously, that is costly.  Currently we are doing this on our development platform.

I agree option one would be preferred as it is the simplest and is database agnostic.  

Do you have a timeline of when this feature will be implemented?  I don't know if it has been started, but I can imagine that it will be somewhat complex.

**Comment by tlaitinen** [comment]
The easiest way to implement this is just to indicate in the .ydsl file that the resulting JSON object should be post-processed by a Haskell function defined elsewhere. This is fairly easy to implement. 

The downside to this approach is that it is not very type-safe as the JSON object's field labels are referenced as strings. However, until a better solution is found and implemented, it may be a viable solution to avoid transferring redundant data.

Later, an extension to the .ydsl select-statement itself could be worked on to allow type-safe post-processing of SQL SELECT's rows.

I'll try to implement the "custom" approach today.

**Comment by tlaitinen** [comment]
I added a new statement which allows to customize the JSON object-to-be-returned in a get handler.

Example:
```
import Handler.Utils (mapEvents)
route /events {
    get {
        select e.id, e.*, u.username
        from Invitation as i
        inner join Event as e
        on i.eventId = e.id
        inner join User as u
        on e.ownerId = u.id
        inner join Multimedia as m on m.eventId = e.id
        where i.userId = $auth.id;
        
       map json with mapEvents; 
    }
}
```

```mapEvents``` has  the type ```forall m. (MonadIO m) => Value -> ReaderT SqlBackend m Value``` it can do quite complex post-processing with the JSON object.

A slight inconvenience is that you need to parse the JSON object and then serialize it again. The issue https://github.com/tlaitinen/yesod-dsl/issues/32 is related and could be useful when implemented.
